### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by yuchen931201** [tank2140896/JavaWeb#1]
你好,请问
`@Autowired
private ModuleDao moduleDao;`
这个报空指针是什么原因?
jdbc.properties配置文件的地址我都填了 我是这样调用的
![Uploading image.png…]()

**Comment by yuchen931201** [comment]
@PostMapping(value="/testInterface",produces={"application/json;charset=UTF-8"})
    @ResponseBody
    public String testInterface(HttpServletRequest request, HttpServletResponse response){
        ModuleServiceImpl moduleService = new ModuleServiceImpl();
        Module module = new Module();
        module.setModuleid("0");
        module.setModulename("haha");
        module.setModuleurl("http://www.baidu.com");
        moduleService.createModule(module);
        return "调用数据库成功";
    }

**Comment by tank2140896** [comment]
testInterface方法如果要调用 ModuleService需要类似这么写：
`
@Autowired
private ModuleService moduleService;
@postmapping(value="/testInterface",produces={"application/json;charset=UTF-8"})
@responsebody
public String testInterface(HttpServletRequest request, HttpServletResponse response){
//ModuleServiceImpl moduleService = new ModuleServiceImpl();
Module module = new Module();
module.setModuleid("0");
module.setModulename("haha");
module.setModuleurl("http://www.baidu.com");
moduleService.createModule(module);
return "调用数据库成功";
}
`
